"""SPEC §6.4–6.5: Feedback — immutable event consumed by Feedback Pipeline."""

from dataclasses import dataclass
from enum import Enum
from typing import Any


class FeedbackSource(Enum):
    """Source of a feedback event."""

    SHELL = "SHELL"
    TEST = "TEST"
    LINT = "LINT"
    DIFF = "DIFF"
    GUARDRAIL = "GUARDRAIL"
    PARSER = "PARSER"
    TOOL_EXECUTOR = "TOOL_EXECUTOR"
    MEMORY = "MEMORY"
    SYSTEM = "SYSTEM"


class Severity(Enum):
    """Severity level of a feedback event."""

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


@dataclass(frozen=True)
class FeedbackMetadata:
    """SPEC §6.5: System-level metadata accompanying a Feedback event.

    provider: LLM provider identifier
    latency_ms: action execution latency
    retry_count: retry count within current iteration
    trace_id: reserved for distributed tracing
    """

    provider: str
    latency_ms: int
    retry_count: int
    trace_id: str | None


@dataclass(frozen=True)
class Feedback:
    """SPEC §6.4: Immutable event representing the result of an execution step.

    Consumed by the Feedback Pipeline. The fingerprint is generated centrally
    by FingerprintStrategy, not by individual generators.

    Constraints:
        - Feedback is immutable (frozen) — once created, cannot be modified.
        - fingerprint is generated by FingerprintStrategy, not by generators.
        - payload contains business semantics; metadata contains system/ops data.
        - Feedback does NOT contain an "action" field — decisions are made by Controllers.
    """

    fingerprint: str
    source: FeedbackSource
    severity: Severity
    payload: dict[str, Any]
    metadata: FeedbackMetadata
    round: int
    timestamp: float
    tool_call: Any | None  # ToolCall | None (forward reference to avoid circular import)
    correlation_id: str | None
